name: CI/CD Pipeline
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Backend
        run: |
          cd backend
          npm install
          npm test
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
      - name: Build Docker Compose
        run: |
          cd infra
          docker-compose build
